require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TvShowsController do
  

  # This should return the minimal set of attributes required to create a valid
  # TvShow. As you add validations to TvShow, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => 'Foo',  :season => 1, :currently_on => false, :channel_id => 107, :last_on => '2011-06-01', :us_season => 1}
  end

  describe "GET index" do
    it "assigns all tv_shows as @tv_shows" do
      tv_show = TvShow.create! valid_attributes
      get :index
      assigns(:tv_shows).should eq([tv_show])
    end
  end

  describe "GET new" do
    it "assigns a new tv_show as @tv_show" do
      get :new
      assigns(:tv_show).should be_a_new(TvShow)
    end
  end

  describe "GET edit" do
    it "assigns the requested tv_show as @tv_show" do
      tv_show = TvShow.create! valid_attributes
      get :edit, :id => tv_show.id.to_s
      assigns(:tv_show).should eq(tv_show)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TvShow" do
        expect {
          post :create, :tv_show => valid_attributes
        }.to change(TvShow, :count).by(1)
      end

      it "assigns a newly created tv_show as @tv_show" do
        post :create, :tv_show => valid_attributes
        assigns(:tv_show).should be_a(TvShow)
        assigns(:tv_show).should be_persisted
      end

      it "redirects to the TV show index page" do
        post :create, :tv_show => valid_attributes
        response.should redirect_to(tv_shows_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tv_show as @tv_show" do
        # Trigger the behavior that occurs when invalid params are submitted
        TvShow.any_instance.stub(:save).and_return(false)
        post :create, :tv_show => {}
        assigns(:tv_show).should be_a_new(TvShow)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TvShow.any_instance.stub(:save).and_return(false)
        post :create, :tv_show => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tv_show" do
        tv_show = TvShow.create! valid_attributes
        # Assuming there are no other tv_shows in the database, this
        # specifies that the TvShow created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TvShow.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tv_show.id, :tv_show => {'these' => 'params'}
      end

      it "assigns the requested tv_show as @tv_show" do
        tv_show = TvShow.create! valid_attributes
        put :update, :id => tv_show.id, :tv_show => valid_attributes
        assigns(:tv_show).should eq(tv_show)
      end

      it "redirects to the TV shows index" do
        tv_show = TvShow.create! valid_attributes
        put :update, :id => tv_show.id, :tv_show => valid_attributes
        response.should redirect_to(tv_shows_url)
      end
    end

    describe "with invalid params" do
      it "assigns the tv_show as @tv_show" do
        tv_show = TvShow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TvShow.any_instance.stub(:save).and_return(false)
        put :update, :id => tv_show.id.to_s, :tv_show => {}
        assigns(:tv_show).should eq(tv_show)
      end

      it "re-renders the 'edit' template" do
        tv_show = TvShow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TvShow.any_instance.stub(:save).and_return(false)
        put :update, :id => tv_show.id.to_s, :tv_show => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tv_show" do
      tv_show = TvShow.create! valid_attributes
      expect {
        delete :destroy, :id => tv_show.id.to_s
      }.to change(TvShow, :count).by(-1)
    end

    it "redirects to the tv_shows list" do
      tv_show = TvShow.create! valid_attributes
      delete :destroy, :id => tv_show.id.to_s
      response.should redirect_to(tv_shows_url)
    end
  end

end
